name: Ampli Implementation Check
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amplitudeinc/ampli
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Verify analytics implementation and update status in Data
          run: ampli status -t ${{secrets.AMPLI_TOKEN}} [--update]
